#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct NetworkConfigDto {
    #[serde(rename = "networkConfig")]
    pub network_config: crate::models::ConfigDto,
}

impl NetworkConfigDto {
    pub fn new(network_config: crate::models::ConfigDto) -> NetworkConfigDto {
        NetworkConfigDto {
            network_config,
        }
    }
}

#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct NetworkConfigBodyDto {
    #[serde(rename = "applyHeightDelta")]
    pub apply_height_delta: Vec<i32>,
    /// Network config like a raw text.
    #[serde(rename = "networkConfig")]
    pub network_config: String,
    /// Allowed versions of transaction in json format.
    #[serde(rename = "supportedEntityVersions")]
    pub supported_entity_versions: String,
}

impl NetworkConfigBodyDto {
    pub fn new(apply_height_delta: Vec<i32>, network_config: String, supported_entity_versions: String) -> NetworkConfigBodyDto {
        NetworkConfigBodyDto {
            apply_height_delta,
            network_config,
            supported_entity_versions,
        }
    }
}

/// NetworkConfigTransactionDto : Transaction that updates config.
#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct NetworkConfigTransactionDto {
    /// The signature of the entity. The signature was generated by the signer and can be used to validate tha the entity data was not modified by a node.
    #[serde(rename = "signature")]
    pub signature: String,
    /// The public key of the entity signer formatted as hexadecimal.
    #[serde(rename = "signer")]
    pub signer: String,
    /// The entity version. The higher byte represents the network identifier: * 0x68 (MAIN_NET) - Public main network. * 0x98 (TEST_NET) - Public test network. * 0x60 (MIJIN) - Private network. * 0x90 (MIJIN_TEST) - Private test network.
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "type")]
    pub _type: crate::models::EntityTypeEnum,
    #[serde(rename = "max_fee")]
    pub max_fee: Vec<i32>,
    #[serde(rename = "deadline")]
    pub deadline: Vec<i32>,
    #[serde(rename = "applyHeightDelta")]
    pub apply_height_delta: Vec<i32>,
    /// Network config like a raw text.
    #[serde(rename = "networkConfig")]
    pub network_config: String,
    /// Allowed versions of transaction in json format.
    #[serde(rename = "supportedEntityVersions")]
    pub supported_entity_versions: String,
}

impl NetworkConfigTransactionDto {
    /// Transaction that updates config.
    pub fn new(signature: String, signer: String, version: i32, _type: crate::models::EntityTypeEnum, max_fee: Vec<i32>, deadline: Vec<i32>, apply_height_delta: Vec<i32>, network_config: String, supported_entity_versions: String) -> NetworkConfigTransactionDto {
        NetworkConfigTransactionDto {
            signature,
            signer,
            version,
            _type,
            max_fee,
            deadline,
            apply_height_delta,
            network_config,
            supported_entity_versions,
        }
    }
}

#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct EmbeddedNetworkConfigTransactionDto {
    /// The public key of the entity signer formatted as hexadecimal.
    #[serde(rename = "signer")]
    pub signer: String,
    /// The entity version. The higher byte represents the network identifier: * 0x68 (MAIN_NET) - Public main network. * 0x98 (TEST_NET) - Public test network. * 0x60 (MIJIN) - Private network. * 0x90 (MIJIN_TEST) - Private test network.
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "type")]
    pub _type: crate::models::EntityTypeEnum,
    #[serde(rename = "max_fee")]
    pub max_fee: Vec<i32>,
    #[serde(rename = "deadline")]
    pub deadline: Vec<i32>,
    #[serde(rename = "applyHeightDelta")]
    pub apply_height_delta: Vec<i32>,
    /// Network config like a raw text.
    #[serde(rename = "networkConfig")]
    pub network_config: String,
    /// Allowed versions of transaction in json format.
    #[serde(rename = "supportedEntityVersions")]
    pub supported_entity_versions: String,
}

impl EmbeddedNetworkConfigTransactionDto {
    pub fn new(signer: String, version: i32, _type: crate::models::EntityTypeEnum, max_fee: Vec<i32>, deadline: Vec<i32>, apply_height_delta: Vec<i32>, network_config: String, supported_entity_versions: String) -> EmbeddedNetworkConfigTransactionDto {
        EmbeddedNetworkConfigTransactionDto {
            signer,
            version,
            _type,
            max_fee,
            deadline,
            apply_height_delta,
            network_config,
            supported_entity_versions,
        }
    }
}

