// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;

use super::*;

use self::flatbuffers::{EndianScalar, Follow};

pub enum DriveFileSystemTransactionBufferOffset {}

#[derive(Copy, Clone, PartialEq)]
pub struct DriveFileSystemTransactionBuffer<'a> {
    pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for DriveFileSystemTransactionBuffer<'a> {
    type Inner = DriveFileSystemTransactionBuffer<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self {
            _tab: flatbuffers::Table::new(buf, loc),
        }
    }
}

impl<'a> DriveFileSystemTransactionBuffer<'a> {
    pub const VT_SIZE_: flatbuffers::VOffsetT = 4;
    pub const VT_SIGNATURE: flatbuffers::VOffsetT = 6;
    pub const VT_SIGNER: flatbuffers::VOffsetT = 8;
    pub const VT_VERSION: flatbuffers::VOffsetT = 10;
    pub const VT_TYPE_: flatbuffers::VOffsetT = 12;
    pub const VT_MAX_FEE: flatbuffers::VOffsetT = 14;
    pub const VT_DEADLINE: flatbuffers::VOffsetT = 16;
    pub const VT_DRIVEKEY: flatbuffers::VOffsetT = 18;
    pub const VT_ROOTHASH: flatbuffers::VOffsetT = 20;
    pub const VT_XORROOTHASH: flatbuffers::VOffsetT = 22;
    pub const VT_ADDACTIONSCOUNT: flatbuffers::VOffsetT = 24;
    pub const VT_REMOVEACTIONSCOUNT: flatbuffers::VOffsetT = 26;
    pub const VT_ADDACTIONS: flatbuffers::VOffsetT = 28;
    pub const VT_REMOVEACTIONS: flatbuffers::VOffsetT = 30;

    #[inline]
    pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        DriveFileSystemTransactionBuffer { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args DriveFileSystemTransactionBufferArgs<'args>,
    ) -> flatbuffers::WIPOffset<DriveFileSystemTransactionBuffer<'bldr>> {
        let mut builder = DriveFileSystemTransactionBufferBuilder::new(_fbb);
        if let Some(x) = args.removeActions {
            builder.add_removeActions(x);
        }
        if let Some(x) = args.addActions {
            builder.add_addActions(x);
        }
        if let Some(x) = args.removeActionsCount {
            builder.add_removeActionsCount(x);
        }
        if let Some(x) = args.addActionsCount {
            builder.add_addActionsCount(x);
        }
        if let Some(x) = args.xorRootHash {
            builder.add_xorRootHash(x);
        }
        if let Some(x) = args.rootHash {
            builder.add_rootHash(x);
        }
        if let Some(x) = args.driveKey {
            builder.add_driveKey(x);
        }
        if let Some(x) = args.deadline {
            builder.add_deadline(x);
        }
        if let Some(x) = args.max_fee {
            builder.add_max_fee(x);
        }
        builder.add_version(args.version);
        if let Some(x) = args.signer {
            builder.add_signer(x);
        }
        if let Some(x) = args.signature {
            builder.add_signature(x);
        }
        builder.add_size_(args.size_);
        builder.add_type_(args.type_);
        builder.finish()
    }

    #[inline]
    pub fn size_(&self) -> u32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<u32>(DriveFileSystemTransactionBuffer::VT_SIZE_, Some(0))
                .unwrap()
        }
    }
    #[inline]
    pub fn signature(&self) -> Option<flatbuffers::Vector<'a, u8>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(
                    DriveFileSystemTransactionBuffer::VT_SIGNATURE,
                    None,
                )
        }
    }
    #[inline]
    pub fn signer(&self) -> Option<flatbuffers::Vector<'a, u8>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(
                    DriveFileSystemTransactionBuffer::VT_SIGNER,
                    None,
                )
        }
    }
    #[inline]
    pub fn version(&self) -> u32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<u32>(DriveFileSystemTransactionBuffer::VT_VERSION, Some(0))
                .unwrap()
        }
    }
    #[inline]
    pub fn type_(&self) -> u16 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<u16>(DriveFileSystemTransactionBuffer::VT_TYPE_, Some(0))
                .unwrap()
        }
    }
    #[inline]
    pub fn max_fee(&self) -> Option<flatbuffers::Vector<'a, u32>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u32>>>(
                    DriveFileSystemTransactionBuffer::VT_MAX_FEE,
                    None,
                )
        }
    }
    #[inline]
    pub fn deadline(&self) -> Option<flatbuffers::Vector<'a, u32>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u32>>>(
                    DriveFileSystemTransactionBuffer::VT_DEADLINE,
                    None,
                )
        }
    }
    #[inline]
    pub fn driveKey(&self) -> Option<flatbuffers::Vector<'a, u8>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(
                    DriveFileSystemTransactionBuffer::VT_DRIVEKEY,
                    None,
                )
        }
    }
    #[inline]
    pub fn rootHash(&self) -> Option<flatbuffers::Vector<'a, u8>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(
                    DriveFileSystemTransactionBuffer::VT_ROOTHASH,
                    None,
                )
        }
    }
    #[inline]
    pub fn xorRootHash(&self) -> Option<flatbuffers::Vector<'a, u8>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(
                    DriveFileSystemTransactionBuffer::VT_XORROOTHASH,
                    None,
                )
        }
    }
    #[inline]
    pub fn addActionsCount(&self) -> Option<flatbuffers::Vector<'a, u8>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(
                    DriveFileSystemTransactionBuffer::VT_ADDACTIONSCOUNT,
                    None,
                )
        }
    }
    #[inline]
    pub fn removeActionsCount(&self) -> Option<flatbuffers::Vector<'a, u8>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(
                    DriveFileSystemTransactionBuffer::VT_REMOVEACTIONSCOUNT,
                    None,
                )
        }
    }
    #[inline]
    pub fn addActions(
        &self,
    ) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<AddActionBuffer<'a>>>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<
                flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<AddActionBuffer>>,
            >>(DriveFileSystemTransactionBuffer::VT_ADDACTIONS, None)
        }
    }
    #[inline]
    pub fn removeActions(
        &self,
    ) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<RemoveActionBuffer<'a>>>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<
                flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<RemoveActionBuffer>>,
            >>(DriveFileSystemTransactionBuffer::VT_REMOVEACTIONS, None)
        }
    }
}

impl flatbuffers::Verifiable for DriveFileSystemTransactionBuffer<'_> {
    #[inline]
    fn run_verifier(
        v: &mut flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
        use self::flatbuffers::Verifiable;
        v.visit_table(pos)?
            .visit_field::<u32>("size_", Self::VT_SIZE_, false)?
            .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>(
                "signature",
                Self::VT_SIGNATURE,
                false,
            )?
            .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>(
                "signer",
                Self::VT_SIGNER,
                false,
            )?
            .visit_field::<u32>("version", Self::VT_VERSION, false)?
            .visit_field::<u16>("type_", Self::VT_TYPE_, false)?
            .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u32>>>(
                "max_fee",
                Self::VT_MAX_FEE,
                false,
            )?
            .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u32>>>(
                "deadline",
                Self::VT_DEADLINE,
                false,
            )?
            .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>(
                "driveKey",
                Self::VT_DRIVEKEY,
                false,
            )?
            .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>(
                "rootHash",
                Self::VT_ROOTHASH,
                false,
            )?
            .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>(
                "xorRootHash",
                Self::VT_XORROOTHASH,
                false,
            )?
            .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>(
                "addActionsCount",
                Self::VT_ADDACTIONSCOUNT,
                false,
            )?
            .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>(
                "removeActionsCount",
                Self::VT_REMOVEACTIONSCOUNT,
                false,
            )?
            .visit_field::<flatbuffers::ForwardsUOffset<
                flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<AddActionBuffer>>,
            >>("addActions", Self::VT_ADDACTIONS, false)?
            .visit_field::<flatbuffers::ForwardsUOffset<
                flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<RemoveActionBuffer>>,
            >>("removeActions", Self::VT_REMOVEACTIONS, false)?
            .finish();
        Ok(())
    }
}

pub struct DriveFileSystemTransactionBufferArgs<'a> {
    pub size_: u32,
    pub signature: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    pub signer: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    pub version: u32,
    pub type_: u16,
    pub max_fee: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u32>>>,
    pub deadline: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u32>>>,
    pub driveKey: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    pub rootHash: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    pub xorRootHash: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    pub addActionsCount: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    pub removeActionsCount: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    pub addActions: Option<
        flatbuffers::WIPOffset<
            flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<AddActionBuffer<'a>>>,
        >,
    >,
    pub removeActions: Option<
        flatbuffers::WIPOffset<
            flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<RemoveActionBuffer<'a>>>,
        >,
    >,
}

impl<'a> Default for DriveFileSystemTransactionBufferArgs<'a> {
    #[inline]
    fn default() -> Self {
        DriveFileSystemTransactionBufferArgs {
            size_: 0,
            signature: None,
            signer: None,
            version: 0,
            type_: 0,
            max_fee: None,
            deadline: None,
            driveKey: None,
            rootHash: None,
            xorRootHash: None,
            addActionsCount: None,
            removeActionsCount: None,
            addActions: None,
            removeActions: None,
        }
    }
}

pub struct DriveFileSystemTransactionBufferBuilder<'a: 'b, 'b> {
    fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}

impl<'a: 'b, 'b> DriveFileSystemTransactionBufferBuilder<'a, 'b> {
    #[inline]
    pub fn add_size_(&mut self, size_: u32) {
        self.fbb_
            .push_slot::<u32>(DriveFileSystemTransactionBuffer::VT_SIZE_, size_, 0);
    }
    #[inline]
    pub fn add_signature(
        &mut self,
        signature: flatbuffers::WIPOffset<flatbuffers::Vector<'b, u8>>,
    ) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            DriveFileSystemTransactionBuffer::VT_SIGNATURE,
            signature,
        );
    }
    #[inline]
    pub fn add_signer(&mut self, signer: flatbuffers::WIPOffset<flatbuffers::Vector<'b, u8>>) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            DriveFileSystemTransactionBuffer::VT_SIGNER,
            signer,
        );
    }
    #[inline]
    pub fn add_version(&mut self, version: u32) {
        self.fbb_
            .push_slot::<u32>(DriveFileSystemTransactionBuffer::VT_VERSION, version, 0);
    }
    #[inline]
    pub fn add_type_(&mut self, type_: u16) {
        self.fbb_
            .push_slot::<u16>(DriveFileSystemTransactionBuffer::VT_TYPE_, type_, 0);
    }
    #[inline]
    pub fn add_max_fee(&mut self, max_fee: flatbuffers::WIPOffset<flatbuffers::Vector<'b, u32>>) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            DriveFileSystemTransactionBuffer::VT_MAX_FEE,
            max_fee,
        );
    }
    #[inline]
    pub fn add_deadline(&mut self, deadline: flatbuffers::WIPOffset<flatbuffers::Vector<'b, u32>>) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            DriveFileSystemTransactionBuffer::VT_DEADLINE,
            deadline,
        );
    }
    #[inline]
    pub fn add_driveKey(&mut self, driveKey: flatbuffers::WIPOffset<flatbuffers::Vector<'b, u8>>) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            DriveFileSystemTransactionBuffer::VT_DRIVEKEY,
            driveKey,
        );
    }
    #[inline]
    pub fn add_rootHash(&mut self, rootHash: flatbuffers::WIPOffset<flatbuffers::Vector<'b, u8>>) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            DriveFileSystemTransactionBuffer::VT_ROOTHASH,
            rootHash,
        );
    }
    #[inline]
    pub fn add_xorRootHash(
        &mut self,
        xorRootHash: flatbuffers::WIPOffset<flatbuffers::Vector<'b, u8>>,
    ) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            DriveFileSystemTransactionBuffer::VT_XORROOTHASH,
            xorRootHash,
        );
    }
    #[inline]
    pub fn add_addActionsCount(
        &mut self,
        addActionsCount: flatbuffers::WIPOffset<flatbuffers::Vector<'b, u8>>,
    ) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            DriveFileSystemTransactionBuffer::VT_ADDACTIONSCOUNT,
            addActionsCount,
        );
    }
    #[inline]
    pub fn add_removeActionsCount(
        &mut self,
        removeActionsCount: flatbuffers::WIPOffset<flatbuffers::Vector<'b, u8>>,
    ) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            DriveFileSystemTransactionBuffer::VT_REMOVEACTIONSCOUNT,
            removeActionsCount,
        );
    }
    #[inline]
    pub fn add_addActions(
        &mut self,
        addActions: flatbuffers::WIPOffset<
            flatbuffers::Vector<'b, flatbuffers::ForwardsUOffset<AddActionBuffer<'b>>>,
        >,
    ) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            DriveFileSystemTransactionBuffer::VT_ADDACTIONS,
            addActions,
        );
    }
    #[inline]
    pub fn add_removeActions(
        &mut self,
        removeActions: flatbuffers::WIPOffset<
            flatbuffers::Vector<'b, flatbuffers::ForwardsUOffset<RemoveActionBuffer<'b>>>,
        >,
    ) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            DriveFileSystemTransactionBuffer::VT_REMOVEACTIONS,
            removeActions,
        );
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    ) -> DriveFileSystemTransactionBufferBuilder<'a, 'b> {
        let start = _fbb.start_table();
        DriveFileSystemTransactionBufferBuilder {
            fbb_: _fbb,
            start_: start,
        }
    }
    #[inline]
    pub fn finish(self) -> flatbuffers::WIPOffset<DriveFileSystemTransactionBuffer<'a>> {
        let o = self.fbb_.end_table(self.start_);
        flatbuffers::WIPOffset::new(o.value())
    }
}

impl core::fmt::Debug for DriveFileSystemTransactionBuffer<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let mut ds = f.debug_struct("DriveFileSystemTransactionBuffer");
        ds.field("size_", &self.size_());
        ds.field("signature", &self.signature());
        ds.field("signer", &self.signer());
        ds.field("version", &self.version());
        ds.field("type_", &self.type_());
        ds.field("max_fee", &self.max_fee());
        ds.field("deadline", &self.deadline());
        ds.field("driveKey", &self.driveKey());
        ds.field("rootHash", &self.rootHash());
        ds.field("xorRootHash", &self.xorRootHash());
        ds.field("addActionsCount", &self.addActionsCount());
        ds.field("removeActionsCount", &self.removeActionsCount());
        ds.field("addActions", &self.addActions());
        ds.field("removeActions", &self.removeActions());
        ds.finish()
    }
}
