// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;

use super::*;

use self::flatbuffers::Follow;

pub enum RemoveExchangeOfferBufferOffset {}

#[derive(Copy, Clone, PartialEq)]
pub struct RemoveExchangeOfferBuffer<'a> {
    pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for RemoveExchangeOfferBuffer<'a> {
    type Inner = RemoveExchangeOfferBuffer<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self { _tab: flatbuffers::Table::new(buf, loc) }
    }
}

impl<'a> RemoveExchangeOfferBuffer<'a> {
    pub const VT_MOSAIC_ID: flatbuffers::VOffsetT = 4;
    pub const VT_TYPE_: flatbuffers::VOffsetT = 6;

    #[inline]
    pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        RemoveExchangeOfferBuffer { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args RemoveExchangeOfferBufferArgs<'args>,
    ) -> flatbuffers::WIPOffset<RemoveExchangeOfferBuffer<'bldr>> {
        let mut builder = RemoveExchangeOfferBufferBuilder::new(_fbb);
        if let Some(x) = args.mosaic_id {
            builder.add_mosaic_id(x);
        }
        builder.add_type_(args.type_);
        builder.finish()
    }

    #[inline]
    pub fn mosaic_id(&self) -> Option<flatbuffers::Vector<'a, u32>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u32>>>(
                RemoveExchangeOfferBuffer::VT_MOSAIC_ID,
                None,
            )
        }
    }
    #[inline]
    pub fn type_(&self) -> u8 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe { self._tab.get::<u8>(RemoveExchangeOfferBuffer::VT_TYPE_, Some(0)).unwrap() }
    }
}

impl flatbuffers::Verifiable for RemoveExchangeOfferBuffer<'_> {
    #[inline]
    fn run_verifier(
        v: &mut flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
        v.visit_table(pos)?
            .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u32>>>(
                "mosaic_id",
                Self::VT_MOSAIC_ID,
                false,
            )?
            .visit_field::<u8>("type_", Self::VT_TYPE_, false)?
            .finish();
        Ok(())
    }
}

pub struct RemoveExchangeOfferBufferArgs<'a> {
    pub mosaic_id: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u32>>>,
    pub type_: u8,
}

impl<'a> Default for RemoveExchangeOfferBufferArgs<'a> {
    #[inline]
    fn default() -> Self {
        RemoveExchangeOfferBufferArgs { mosaic_id: None, type_: 0 }
    }
}

pub struct RemoveExchangeOfferBufferBuilder<'a: 'b, 'b> {
    fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}

impl<'a: 'b, 'b> RemoveExchangeOfferBufferBuilder<'a, 'b> {
    #[inline]
    pub fn add_mosaic_id(
        &mut self,
        mosaic_id: flatbuffers::WIPOffset<flatbuffers::Vector<'b, u32>>,
    ) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            RemoveExchangeOfferBuffer::VT_MOSAIC_ID,
            mosaic_id,
        );
    }
    #[inline]
    pub fn add_type_(&mut self, type_: u8) {
        self.fbb_.push_slot::<u8>(RemoveExchangeOfferBuffer::VT_TYPE_, type_, 0);
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    ) -> RemoveExchangeOfferBufferBuilder<'a, 'b> {
        let start = _fbb.start_table();
        RemoveExchangeOfferBufferBuilder { fbb_: _fbb, start_: start }
    }
    #[inline]
    pub fn finish(self) -> flatbuffers::WIPOffset<RemoveExchangeOfferBuffer<'a>> {
        let o = self.fbb_.end_table(self.start_);
        flatbuffers::WIPOffset::new(o.value())
    }
}

impl core::fmt::Debug for RemoveExchangeOfferBuffer<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let mut ds = f.debug_struct("RemoveExchangeOfferBuffer");
        ds.field("mosaic_id", &self.mosaic_id());
        ds.field("type_", &self.type_());
        ds.finish()
    }
}
