// automatically generated by the FlatBuffers compiler, do not modify
// @generated
extern crate alloc;
extern crate flatbuffers;

use super::*;

use self::flatbuffers::Follow;

pub enum TransferTransactionBufferOffset {}

#[derive(Copy, Clone, PartialEq)]
pub struct TransferTransactionBuffer<'a> {
    pub _tab: flatbuffers::Table<'a>,
}

impl<'a> flatbuffers::Follow<'a> for TransferTransactionBuffer<'a> {
    type Inner = TransferTransactionBuffer<'a>;
    #[inline]
    unsafe fn follow(buf: &'a [u8], loc: usize) -> Self::Inner {
        Self { _tab: flatbuffers::Table::new(buf, loc) }
    }
}

impl<'a> TransferTransactionBuffer<'a> {
    pub const VT_SIZE_: flatbuffers::VOffsetT = 4;
    pub const VT_SIGNATURE: flatbuffers::VOffsetT = 6;
    pub const VT_SIGNER: flatbuffers::VOffsetT = 8;
    pub const VT_VERSION: flatbuffers::VOffsetT = 10;
    pub const VT_TYPE_: flatbuffers::VOffsetT = 12;
    pub const VT_MAX_FEE: flatbuffers::VOffsetT = 14;
    pub const VT_DEADLINE: flatbuffers::VOffsetT = 16;
    pub const VT_RECIPIENT: flatbuffers::VOffsetT = 18;
    pub const VT_MESSAGE_SIZE: flatbuffers::VOffsetT = 20;
    pub const VT_NUM_MOSAICS: flatbuffers::VOffsetT = 22;
    pub const VT_MESSAGE: flatbuffers::VOffsetT = 24;
    pub const VT_MOSAICS: flatbuffers::VOffsetT = 26;

    #[inline]
    pub unsafe fn init_from_table(table: flatbuffers::Table<'a>) -> Self {
        TransferTransactionBuffer { _tab: table }
    }
    #[allow(unused_mut)]
    pub fn create<'bldr: 'args, 'args: 'mut_bldr, 'mut_bldr>(
        _fbb: &'mut_bldr mut flatbuffers::FlatBufferBuilder<'bldr>,
        args: &'args TransferTransactionBufferArgs<'args>,
    ) -> flatbuffers::WIPOffset<TransferTransactionBuffer<'bldr>> {
        let mut builder = TransferTransactionBufferBuilder::new(_fbb);
        if let Some(x) = args.mosaics {
            builder.add_mosaics(x);
        }
        if let Some(x) = args.message {
            builder.add_message(x);
        }
        if let Some(x) = args.recipient {
            builder.add_recipient(x);
        }
        if let Some(x) = args.deadline {
            builder.add_deadline(x);
        }
        if let Some(x) = args.max_fee {
            builder.add_max_fee(x);
        }
        builder.add_version(args.version);
        if let Some(x) = args.signer {
            builder.add_signer(x);
        }
        if let Some(x) = args.signature {
            builder.add_signature(x);
        }
        builder.add_size_(args.size_);
        builder.add_message_size(args.message_size);
        builder.add_type_(args.type_);
        builder.add_num_mosaics(args.num_mosaics);
        builder.finish()
    }

    #[inline]
    pub fn size_(&self) -> u32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe { self._tab.get::<u32>(TransferTransactionBuffer::VT_SIZE_, Some(0)).unwrap() }
    }
    #[inline]
    pub fn signature(&self) -> Option<flatbuffers::Vector<'a, u8>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(
                TransferTransactionBuffer::VT_SIGNATURE,
                None,
            )
        }
    }
    #[inline]
    pub fn signer(&self) -> Option<flatbuffers::Vector<'a, u8>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(
                TransferTransactionBuffer::VT_SIGNER,
                None,
            )
        }
    }
    #[inline]
    pub fn version(&self) -> u32 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe { self._tab.get::<u32>(TransferTransactionBuffer::VT_VERSION, Some(0)).unwrap() }
    }
    #[inline]
    pub fn type_(&self) -> u16 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe { self._tab.get::<u16>(TransferTransactionBuffer::VT_TYPE_, Some(0)).unwrap() }
    }
    #[inline]
    pub fn max_fee(&self) -> Option<flatbuffers::Vector<'a, u32>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u32>>>(
                TransferTransactionBuffer::VT_MAX_FEE,
                None,
            )
        }
    }
    #[inline]
    pub fn deadline(&self) -> Option<flatbuffers::Vector<'a, u32>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u32>>>(
                TransferTransactionBuffer::VT_DEADLINE,
                None,
            )
        }
    }
    #[inline]
    pub fn recipient(&self) -> Option<flatbuffers::Vector<'a, u8>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'a, u8>>>(
                TransferTransactionBuffer::VT_RECIPIENT,
                None,
            )
        }
    }
    #[inline]
    pub fn message_size(&self) -> u16 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab
                .get::<u16>(TransferTransactionBuffer::VT_MESSAGE_SIZE, Some(0))
                .unwrap()
        }
    }
    #[inline]
    pub fn num_mosaics(&self) -> u8 {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe { self._tab.get::<u8>(TransferTransactionBuffer::VT_NUM_MOSAICS, Some(0)).unwrap() }
    }
    #[inline]
    pub fn message(&self) -> Option<MessageBuffer<'a>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<MessageBuffer>>(
                TransferTransactionBuffer::VT_MESSAGE,
                None,
            )
        }
    }
    #[inline]
    pub fn mosaics(
        &self,
    ) -> Option<flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<MosaicBuffer<'a>>>> {
        // Safety:
        // Created from valid Table for this object
        // which contains a valid value in this slot
        unsafe {
            self._tab.get::<flatbuffers::ForwardsUOffset<
                flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<MosaicBuffer>>,
            >>(TransferTransactionBuffer::VT_MOSAICS, None)
        }
    }
}

impl flatbuffers::Verifiable for TransferTransactionBuffer<'_> {
    #[inline]
    fn run_verifier(
        v: &mut flatbuffers::Verifier,
        pos: usize,
    ) -> Result<(), flatbuffers::InvalidFlatbuffer> {
        v.visit_table(pos)?
            .visit_field::<u32>("size_", Self::VT_SIZE_, false)?
            .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>(
                "signature",
                Self::VT_SIGNATURE,
                false,
            )?
            .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>(
                "signer",
                Self::VT_SIGNER,
                false,
            )?
            .visit_field::<u32>("version", Self::VT_VERSION, false)?
            .visit_field::<u16>("type_", Self::VT_TYPE_, false)?
            .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u32>>>(
                "max_fee",
                Self::VT_MAX_FEE,
                false,
            )?
            .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u32>>>(
                "deadline",
                Self::VT_DEADLINE,
                false,
            )?
            .visit_field::<flatbuffers::ForwardsUOffset<flatbuffers::Vector<'_, u8>>>(
                "recipient",
                Self::VT_RECIPIENT,
                false,
            )?
            .visit_field::<u16>("message_size", Self::VT_MESSAGE_SIZE, false)?
            .visit_field::<u8>("num_mosaics", Self::VT_NUM_MOSAICS, false)?
            .visit_field::<flatbuffers::ForwardsUOffset<MessageBuffer>>(
                "message",
                Self::VT_MESSAGE,
                false,
            )?
            .visit_field::<flatbuffers::ForwardsUOffset<
                flatbuffers::Vector<'_, flatbuffers::ForwardsUOffset<MosaicBuffer>>,
            >>("mosaics", Self::VT_MOSAICS, false)?
            .finish();
        Ok(())
    }
}

pub struct TransferTransactionBufferArgs<'a> {
    pub size_: u32,
    pub signature: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    pub signer: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    pub version: u32,
    pub type_: u16,
    pub max_fee: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u32>>>,
    pub deadline: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u32>>>,
    pub recipient: Option<flatbuffers::WIPOffset<flatbuffers::Vector<'a, u8>>>,
    pub message_size: u16,
    pub num_mosaics: u8,
    pub message: Option<flatbuffers::WIPOffset<MessageBuffer<'a>>>,
    pub mosaics: Option<
        flatbuffers::WIPOffset<
            flatbuffers::Vector<'a, flatbuffers::ForwardsUOffset<MosaicBuffer<'a>>>,
        >,
    >,
}

impl<'a> Default for TransferTransactionBufferArgs<'a> {
    #[inline]
    fn default() -> Self {
        TransferTransactionBufferArgs {
            size_: 0,
            signature: None,
            signer: None,
            version: 0,
            type_: 0,
            max_fee: None,
            deadline: None,
            recipient: None,
            message_size: 0,
            num_mosaics: 0,
            message: None,
            mosaics: None,
        }
    }
}

pub struct TransferTransactionBufferBuilder<'a: 'b, 'b> {
    fbb_: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    start_: flatbuffers::WIPOffset<flatbuffers::TableUnfinishedWIPOffset>,
}

impl<'a: 'b, 'b> TransferTransactionBufferBuilder<'a, 'b> {
    #[inline]
    pub fn add_size_(&mut self, size_: u32) {
        self.fbb_.push_slot::<u32>(TransferTransactionBuffer::VT_SIZE_, size_, 0);
    }
    #[inline]
    pub fn add_signature(
        &mut self,
        signature: flatbuffers::WIPOffset<flatbuffers::Vector<'b, u8>>,
    ) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            TransferTransactionBuffer::VT_SIGNATURE,
            signature,
        );
    }
    #[inline]
    pub fn add_signer(&mut self, signer: flatbuffers::WIPOffset<flatbuffers::Vector<'b, u8>>) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            TransferTransactionBuffer::VT_SIGNER,
            signer,
        );
    }
    #[inline]
    pub fn add_version(&mut self, version: u32) {
        self.fbb_.push_slot::<u32>(TransferTransactionBuffer::VT_VERSION, version, 0);
    }
    #[inline]
    pub fn add_type_(&mut self, type_: u16) {
        self.fbb_.push_slot::<u16>(TransferTransactionBuffer::VT_TYPE_, type_, 0);
    }
    #[inline]
    pub fn add_max_fee(&mut self, max_fee: flatbuffers::WIPOffset<flatbuffers::Vector<'b, u32>>) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            TransferTransactionBuffer::VT_MAX_FEE,
            max_fee,
        );
    }
    #[inline]
    pub fn add_deadline(&mut self, deadline: flatbuffers::WIPOffset<flatbuffers::Vector<'b, u32>>) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            TransferTransactionBuffer::VT_DEADLINE,
            deadline,
        );
    }
    #[inline]
    pub fn add_recipient(
        &mut self,
        recipient: flatbuffers::WIPOffset<flatbuffers::Vector<'b, u8>>,
    ) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            TransferTransactionBuffer::VT_RECIPIENT,
            recipient,
        );
    }
    #[inline]
    pub fn add_message_size(&mut self, message_size: u16) {
        self.fbb_
            .push_slot::<u16>(TransferTransactionBuffer::VT_MESSAGE_SIZE, message_size, 0);
    }
    #[inline]
    pub fn add_num_mosaics(&mut self, num_mosaics: u8) {
        self.fbb_
            .push_slot::<u8>(TransferTransactionBuffer::VT_NUM_MOSAICS, num_mosaics, 0);
    }
    #[inline]
    pub fn add_message(&mut self, message: flatbuffers::WIPOffset<MessageBuffer<'b>>) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<MessageBuffer>>(
            TransferTransactionBuffer::VT_MESSAGE,
            message,
        );
    }
    #[inline]
    pub fn add_mosaics(
        &mut self,
        mosaics: flatbuffers::WIPOffset<
            flatbuffers::Vector<'b, flatbuffers::ForwardsUOffset<MosaicBuffer<'b>>>,
        >,
    ) {
        self.fbb_.push_slot_always::<flatbuffers::WIPOffset<_>>(
            TransferTransactionBuffer::VT_MOSAICS,
            mosaics,
        );
    }
    #[inline]
    pub fn new(
        _fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    ) -> TransferTransactionBufferBuilder<'a, 'b> {
        let start = _fbb.start_table();
        TransferTransactionBufferBuilder { fbb_: _fbb, start_: start }
    }
    #[inline]
    pub fn finish(self) -> flatbuffers::WIPOffset<TransferTransactionBuffer<'a>> {
        let o = self.fbb_.end_table(self.start_);
        flatbuffers::WIPOffset::new(o.value())
    }
}

impl core::fmt::Debug for TransferTransactionBuffer<'_> {
    fn fmt(&self, f: &mut core::fmt::Formatter<'_>) -> core::fmt::Result {
        let mut ds = f.debug_struct("TransferTransactionBuffer");
        ds.field("size_", &self.size_());
        ds.field("signature", &self.signature());
        ds.field("signer", &self.signer());
        ds.field("version", &self.version());
        ds.field("type_", &self.type_());
        ds.field("max_fee", &self.max_fee());
        ds.field("deadline", &self.deadline());
        ds.field("recipient", &self.recipient());
        ds.field("message_size", &self.message_size());
        ds.field("num_mosaics", &self.num_mosaics());
        ds.field("message", &self.message());
        ds.field("mosaics", &self.mosaics());
        ds.finish()
    }
}

#[inline]
/// Verifies that a buffer of bytes contains a `TransferTransactionBuffer`
/// and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_transfer_transaction_buffer_unchecked`.
pub fn root_as_transfer_transaction_buffer(
    buf: &[u8],
) -> Result<TransferTransactionBuffer, flatbuffers::InvalidFlatbuffer> {
    flatbuffers::root::<TransferTransactionBuffer>(buf)
}

#[inline]
/// Verifies that a buffer of bytes contains a size prefixed
/// `TransferTransactionBuffer` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `size_prefixed_root_as_transfer_transaction_buffer_unchecked`.
pub fn size_prefixed_root_as_transfer_transaction_buffer(
    buf: &[u8],
) -> Result<TransferTransactionBuffer, flatbuffers::InvalidFlatbuffer> {
    flatbuffers::size_prefixed_root::<TransferTransactionBuffer>(buf)
}

#[inline]
/// Verifies, with the given options, that a buffer of bytes
/// contains a `TransferTransactionBuffer` and returns it.
/// Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_transfer_transaction_buffer_unchecked`.
pub fn root_as_transfer_transaction_buffer_with_opts<'b, 'o>(
    opts: &'o flatbuffers::VerifierOptions,
    buf: &'b [u8],
) -> Result<TransferTransactionBuffer<'b>, flatbuffers::InvalidFlatbuffer> {
    flatbuffers::root_with_opts::<TransferTransactionBuffer<'b>>(opts, buf)
}

#[inline]
/// Verifies, with the given verifier options, that a buffer of
/// bytes contains a size prefixed `TransferTransactionBuffer` and returns
/// it. Note that verification is still experimental and may not
/// catch every error, or be maximally performant. For the
/// previous, unchecked, behavior use
/// `root_as_transfer_transaction_buffer_unchecked`.
pub fn size_prefixed_root_as_transfer_transaction_buffer_with_opts<'b, 'o>(
    opts: &'o flatbuffers::VerifierOptions,
    buf: &'b [u8],
) -> Result<TransferTransactionBuffer<'b>, flatbuffers::InvalidFlatbuffer> {
    flatbuffers::size_prefixed_root_with_opts::<TransferTransactionBuffer<'b>>(opts, buf)
}

#[inline]
/// Assumes, without verification, that a buffer of bytes contains a TransferTransactionBuffer and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid `TransferTransactionBuffer`.
pub unsafe fn root_as_transfer_transaction_buffer_unchecked(
    buf: &[u8],
) -> TransferTransactionBuffer {
    flatbuffers::root_unchecked::<TransferTransactionBuffer>(buf)
}

#[inline]
/// Assumes, without verification, that a buffer of bytes contains a size prefixed TransferTransactionBuffer and returns it.
/// # Safety
/// Callers must trust the given bytes do indeed contain a valid size prefixed `TransferTransactionBuffer`.
pub unsafe fn size_prefixed_root_as_transfer_transaction_buffer_unchecked(
    buf: &[u8],
) -> TransferTransactionBuffer {
    flatbuffers::size_prefixed_root_unchecked::<TransferTransactionBuffer>(buf)
}

#[inline]
pub fn finish_transfer_transaction_buffer_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<TransferTransactionBuffer<'a>>,
) {
    fbb.finish(root, None);
}

#[inline]
pub fn finish_size_prefixed_transfer_transaction_buffer_buffer<'a, 'b>(
    fbb: &'b mut flatbuffers::FlatBufferBuilder<'a>,
    root: flatbuffers::WIPOffset<TransferTransactionBuffer<'a>>,
) {
    fbb.finish_size_prefixed(root, None);
}
