use crate::models::blockchain::block_model::{HeightInfo, BlockchainScore};
use crate::models::Uint64Dto;

#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub(crate) struct HeightInfoDto {
    #[serde(rename = "height")]
    height: Uint64Dto,
}

impl HeightInfoDto {
    pub fn to_struct(&self) -> HeightInfo {
        HeightInfo {
            height: self.height.to_struct()
        }
    }
}

#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub(crate) struct BlockchainScoreDto {
    #[serde(rename = "scoreHigh")]
    score_high: Uint64Dto,
    #[serde(rename = "scoreLow")]
    score_low: Uint64Dto,
}

impl BlockchainScoreDto {
    pub fn to_struct(&self) -> BlockchainScore {
        BlockchainScore {
            score_high: self.score_high.to_struct(),
            score_low: self.score_low.to_struct()
        }
    }
}

#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub(crate) struct BlockchainUpgradeBodyDto {
    #[serde(rename = "upgradePeriod")]
    upgrade_period: Vec<i32>,
    #[serde(rename = "newBlockChainVersion")]
    new_block_chain_version: Vec<i32>,
}

impl BlockchainUpgradeBodyDto {
    pub fn new(upgrade_period: Vec<i32>, new_block_chain_version: Vec<i32>) -> BlockchainUpgradeBodyDto {
        BlockchainUpgradeBodyDto {
            upgrade_period,
            new_block_chain_version,
        }
    }
}

#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub(crate) struct BlockchainUpgradeDto {
    #[serde(rename = "blockchainUpgrade")]
    blockchain_upgrade: crate::models::UpgradeDto,
}

impl BlockchainUpgradeDto {
    pub fn new(blockchain_upgrade: crate::models::UpgradeDto) -> BlockchainUpgradeDto {
        BlockchainUpgradeDto {
            blockchain_upgrade,
        }
    }
}

/// BlockchainUpgradeTransactionDto : Transaction that change version of blockchain.
#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub(crate) struct BlockchainUpgradeTransactionDto {
    /// The signature of the entity. The signature was generated by the signer and can be used to validate tha the entity data was not modified by a node.
    #[serde(rename = "signature")]
    signature: String,
    /// The public key of the entity signer formatted as hexadecimal.
    #[serde(rename = "signer")]
    signer: String,
    /// The entity version. The higher byte represents the network identifier: * 0x68 (MAIN_NET) - PUBLIC main network. * 0x98 (TEST_NET) - PUBLIC test network. * 0x60 (MIJIN) - PRIVATE network. * 0x90 (MIJIN_TEST) - PRIVATE test network.
    #[serde(rename = "version")]
    version: i32,
    #[serde(rename = "type")]
    _type: crate::models::EntityTypeEnum,
    #[serde(rename = "max_fee")]
    max_fee: Vec<i32>,
    #[serde(rename = "deadline")]
    deadline: Vec<i32>,
    #[serde(rename = "upgradePeriod")]
    upgrade_period: Vec<i32>,
    #[serde(rename = "newBlockChainVersion")]
    new_block_chain_version: Vec<i32>,
}

impl BlockchainUpgradeTransactionDto {
    /// Transaction that change version of blockchain.
    pub fn new(signature: String, signer: String, version: i32, _type: crate::models::EntityTypeEnum, max_fee: Vec<i32>, deadline: Vec<i32>, upgrade_period: Vec<i32>, new_block_chain_version: Vec<i32>) -> BlockchainUpgradeTransactionDto {
        BlockchainUpgradeTransactionDto {
            signature,
            signer,
            version,
            _type,
            max_fee,
            deadline,
            upgrade_period,
            new_block_chain_version,
        }
    }
}

#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct EmbeddedBlockchainUpgradeTransactionDto {
    /// The public key of the entity signer formatted as hexadecimal.
    #[serde(rename = "signer")]
    signer: String,
    /// The entity version. The higher byte represents the network identifier: * 0x68 (MAIN_NET) - PUBLIC main network. * 0x98 (TEST_NET) - PUBLIC test network. * 0x60 (MIJIN) - PRIVATE network. * 0x90 (MIJIN_TEST) - PRIVATE test network.
    #[serde(rename = "version")]
    version: i32,
    #[serde(rename = "type")]
    _type: crate::models::EntityTypeEnum,
    #[serde(rename = "max_fee")]
    max_fee: Vec<i32>,
    #[serde(rename = "deadline")]
    deadline: Vec<i32>,
    #[serde(rename = "upgradePeriod")]
    upgrade_period: Vec<i32>,
    #[serde(rename = "newBlockChainVersion")]
    new_block_chain_version: Vec<i32>,
}

impl EmbeddedBlockchainUpgradeTransactionDto {
    pub fn new(signer: String, version: i32, _type: crate::models::EntityTypeEnum, max_fee: Vec<i32>, deadline: Vec<i32>, upgrade_period: Vec<i32>, new_block_chain_version: Vec<i32>) -> EmbeddedBlockchainUpgradeTransactionDto {
        EmbeddedBlockchainUpgradeTransactionDto {
            signer,
            version,
            _type,
            max_fee,
            deadline,
            upgrade_period,
            new_block_chain_version,
        }
    }
}

