#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct HeightInfoDto {
    #[serde(rename = "height")]
    pub height: Vec<i32>,
}

impl HeightInfoDto {
    pub fn new(height: Vec<i32>) -> HeightInfoDto {
        HeightInfoDto {
            height,
        }
    }
}

#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockchainScoreDto {
    #[serde(rename = "scoreHigh")]
    pub score_high: Vec<i32>,
    #[serde(rename = "scoreLow")]
    pub score_low: Vec<i32>,
}

impl BlockchainScoreDto {
    pub fn new(score_high: Vec<i32>, score_low: Vec<i32>) -> BlockchainScoreDto {
        BlockchainScoreDto {
            score_high,
            score_low,
        }
    }
}

#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockchainUpgradeBodyDto {
    #[serde(rename = "upgradePeriod")]
    pub upgrade_period: Vec<i32>,
    #[serde(rename = "newBlockChainVersion")]
    pub new_block_chain_version: Vec<i32>,
}

impl BlockchainUpgradeBodyDto {
    pub fn new(upgrade_period: Vec<i32>, new_block_chain_version: Vec<i32>) -> BlockchainUpgradeBodyDto {
        BlockchainUpgradeBodyDto {
            upgrade_period,
            new_block_chain_version,
        }
    }
}

#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockchainUpgradeDto {
    #[serde(rename = "blockchainUpgrade")]
    pub blockchain_upgrade: crate::models::UpgradeDto,
}

impl BlockchainUpgradeDto {
    pub fn new(blockchain_upgrade: crate::models::UpgradeDto) -> BlockchainUpgradeDto {
        BlockchainUpgradeDto {
            blockchain_upgrade,
        }
    }
}

/// BlockchainUpgradeTransactionDto : Transaction that change version of blockchain.
#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct BlockchainUpgradeTransactionDto {
    /// The signature of the entity. The signature was generated by the signer and can be used to validate tha the entity data was not modified by a node.
    #[serde(rename = "signature")]
    pub signature: String,
    /// The public key of the entity signer formatted as hexadecimal.
    #[serde(rename = "signer")]
    pub signer: String,
    /// The entity version. The higher byte represents the network identifier: * 0x68 (MAIN_NET) - PUBLIC main network. * 0x98 (TEST_NET) - PUBLIC test network. * 0x60 (MIJIN) - PRIVATE network. * 0x90 (MIJIN_TEST) - PRIVATE test network.
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "type")]
    pub _type: crate::models::EntityTypeEnum,
    #[serde(rename = "max_fee")]
    pub max_fee: Vec<i32>,
    #[serde(rename = "deadline")]
    pub deadline: Vec<i32>,
    #[serde(rename = "upgradePeriod")]
    pub upgrade_period: Vec<i32>,
    #[serde(rename = "newBlockChainVersion")]
    pub new_block_chain_version: Vec<i32>,
}

impl BlockchainUpgradeTransactionDto {
    /// Transaction that change version of blockchain.
    pub fn new(signature: String, signer: String, version: i32, _type: crate::models::EntityTypeEnum, max_fee: Vec<i32>, deadline: Vec<i32>, upgrade_period: Vec<i32>, new_block_chain_version: Vec<i32>) -> BlockchainUpgradeTransactionDto {
        BlockchainUpgradeTransactionDto {
            signature,
            signer,
            version,
            _type,
            max_fee,
            deadline,
            upgrade_period,
            new_block_chain_version,
        }
    }
}

#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct EmbeddedBlockchainUpgradeTransactionDto {
    /// The public key of the entity signer formatted as hexadecimal.
    #[serde(rename = "signer")]
    pub signer: String,
    /// The entity version. The higher byte represents the network identifier: * 0x68 (MAIN_NET) - PUBLIC main network. * 0x98 (TEST_NET) - PUBLIC test network. * 0x60 (MIJIN) - PRIVATE network. * 0x90 (MIJIN_TEST) - PRIVATE test network.
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "type")]
    pub _type: crate::models::EntityTypeEnum,
    #[serde(rename = "max_fee")]
    pub max_fee: Vec<i32>,
    #[serde(rename = "deadline")]
    pub deadline: Vec<i32>,
    #[serde(rename = "upgradePeriod")]
    pub upgrade_period: Vec<i32>,
    #[serde(rename = "newBlockChainVersion")]
    pub new_block_chain_version: Vec<i32>,
}

impl EmbeddedBlockchainUpgradeTransactionDto {
    pub fn new(signer: String, version: i32, _type: crate::models::EntityTypeEnum, max_fee: Vec<i32>, deadline: Vec<i32>, upgrade_period: Vec<i32>, new_block_chain_version: Vec<i32>) -> EmbeddedBlockchainUpgradeTransactionDto {
        EmbeddedBlockchainUpgradeTransactionDto {
            signer,
            version,
            _type,
            max_fee,
            deadline,
            upgrade_period,
            new_block_chain_version,
        }
    }
}

