use crate::models::uint_64::Uint64Dto;

use super::transaction::EmbeddedTransactionInfoDto;
use crate::models::multisig::CosignatureDto;

/// AggregateTransactionDto : Transaction that combines multiple transactions together.
#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct AggregateTransactionDto {
    /// The signature of the entity. The signature was generated by the signer and can be used to validate tha the entity data was not modified by a node. 
    #[serde(rename = "signature")]
    pub signature: String,
    /// The public key of the entity signer formatted as hexadecimal.
    #[serde(rename = "signer")]
    pub signer: String,
    /// The entity version. The higher byte represents the network identifier: * 0x68 (MAIN_NET) - PUBLIC main network. * 0x98 (TEST_NET) - PUBLIC test network. * 0x60 (MIJIN) - PRIVATE network. * 0x90 (MIJIN_TEST) - PRIVATE test network.
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "type")]
    pub _type: u16,
    #[serde(rename = "max_fee")]
    pub max_fee: Uint64Dto,
    #[serde(rename = "deadline")]
    pub deadline: Uint64Dto,
    /// An array of transaction cosignatures.
    #[serde(rename = "cosignatures")]
    pub cosignatures: Vec<CosignatureDto>,
    /// The array of transactions initiated by different accounts.
    #[serde(rename = "transactions")]
    pub transactions: Vec<EmbeddedTransactionInfoDto>,
}

#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct AggregateTransactionBodyDto {
    /// An array of transaction cosignatures.
    #[serde(rename = "cosignatures")]
    pub cosignatures: Vec<CosignatureDto>,
    /// The array of transactions initiated by different accounts.
    #[serde(rename = "transactions")]
    pub transactions: Vec<EmbeddedTransactionInfoDto>,
}
