#[derive(Debug, PartialEq, Serialize, Deserialize)]
pub struct EmbeddedHashLockTransactionDto {
    /// The public key of the entity signer formatted as hexadecimal.
    #[serde(rename = "signer")]
    pub signer: String,
    /// The entity version. The higher byte represents the network identifier: * 0x68 (MAIN_NET) - Public main network. * 0x98 (TEST_NET) - Public test network. * 0x60 (MIJIN) - Private network. * 0x90 (MIJIN_TEST) - Private test network. 
    #[serde(rename = "version")]
    pub version: i32,
    #[serde(rename = "type")]
    pub _type: crate::models::EntityTypeEnum,
    #[serde(rename = "max_fee")]
    pub max_fee: Vec<i32>,
    #[serde(rename = "deadline")]
    pub deadline: Vec<i32>,
    /// The signature of the entity. The signature was generated by the signer and can be used to validate tha the entity data was not modified by a node. 
    #[serde(rename = "signature")]
    pub signature: String,
    #[serde(rename = "mosaic")]
    pub mosaic: crate::models::MosaicDto,
    #[serde(rename = "duration")]
    pub duration: crate::models::MosaicDto,
    /// The aggregate bonded transaction hash that has to be confirmed before unlocking the mosaics. 
    #[serde(rename = "hash")]
    pub hash: String,
}

impl EmbeddedHashLockTransactionDto {
    pub fn new(signer: String, version: i32, _type: crate::models::EntityTypeEnum, max_fee: Vec<i32>, deadline: Vec<i32>, signature: String, mosaic: crate::models::MosaicDto, duration: crate::models::MosaicDto, hash: String) -> EmbeddedHashLockTransactionDto {
        EmbeddedHashLockTransactionDto {
            signer,
            version,
            _type,
            max_fee,
            deadline,
            signature,
            mosaic,
            duration,
            hash,
        }
    }
}


